module.exports = {
  OK: { code: 200, message: 'OK' },
  CREATED: { code: 201, message: 'Created' },
  ACCEPTED: { code: 202, message: 'Accepted' },
  NO_CONTENT: { code: 204, message: 'No Content' },
  MOVED_PERMANENTLY: { code: 301, message: 'Moved Permanently' },
  SEE_OTHER: { code: 303, message: 'See Other' },
  NOT_MODIFIED: { code: 304, message: 'Not Modified' },
  TEMPORARY_REDIRECT: { code: 307, message: 'Temporary Redirect' },
  BAD_REQUEST: { code: 400, message: 'Bad Request' },
  UNAUTHORIZED: { code: 401, message: 'Unauthorized' },
  FORBIDDEN: { code: 403, message: 'Forbidden' },
  NOT_FOUND: { code: 404, message: 'Not Found' },
  METHOD_NOT_ALLOWED: { code: 405, message: 'Method Not Allowed' },
  NOT_ACCEPTABLE: { code: 406, message: 'Not Acceptable' },
  CONFLICT: { code: 409, message: 'Conflict' },
  PRECONDITION_FAILED: { code: 412, message: 'Precondition Failed' },
  UNSUPPORTED_MEDIA_TYPE: { code: 415, message: 'Unsupported Media Type' },
  INTERNAL_SERVER_ERROR: { code: 500, message: 'Internal Server Error' },
};
